### ISSUE TITLE
FR: support for Statamic v4

### ISSUE THREAD

**Issue by wesort** [mariovass/statamic-uuid#14]
Any plans to support v4? 

Thanks.

**Comment by aryehraber** [comment]
Most definitely! Apologies for the delay, been rather busy, but will try to prioritise ASAP.

**Comment by aryehraber** [comment]
@wesort Just released v2.2.0 which now supports Statamic 4! Let me know if you encounter any issues.

**Comment by wesort** [comment]
Wow that was quick! Thanks.
