### ISSUE TITLE
Read only doesn't work

### ISSUE THREAD

**Issue by edalzell** [mariovass/statamic-uuid#6]
In Statamic v3, to make a field read only, you set `read_only` to true. This show as read only the CP but isn't actually read-only.

**Comment by aryehraber** [comment]
Uuid supports read-only fields using `readonly: true` (outlined in [Usage section of docs](https://github.com/serieseight/statamic-uuid#usage)) and is also a setting inside the CP Blueprint builder. However, I can see why you got confused, so will add support for `read_only` as well.

FYI: I can't seem to find anything regarding `read_only` being supported in Statamic's own fields in the docs, probably worth a mention somewhere and/or make it findable via the docs search.

**Comment by edalzell** [comment]
> FYI: I can't seem to find anything regarding `read_only` being supported in Statamic's own fields in the docs, probably worth a mention somewhere and/or make it findable via the docs search.

Ya it's not documented, yet.
